ppe_app/models.py
from datetime import datetime

from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

from . import db, login_manager


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    role = db.Column(db.String(20), default='employee')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Violation(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    image_path = db.Column(db.String(200))
    description = db.Column(db.String(200))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', backref='violations')

ppe_app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    role = StringField('Role', default='employee')
    submit = SubmitField('Register')


class UploadForm(FlaskForm):
    image = FileField('Image', validators=[DataRequired()])
    submit = SubmitField('Upload')

ppe_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager


# Initialize extensions
login_manager = LoginManager()
db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'change-this-secret'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///ppe.db'

    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'login'

    from . import routes  # noqa: W503
    app.register_blueprint(routes.bp)

    with app.app_context():
        db.create_all()

    return app

ppe_app/routes.py
import os
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.utils import secure_filename

from . import db
from .forms import LoginForm, RegistrationForm, UploadForm
from .models import User
from .utils import detect_helmet, save_violation, capture_image_from_ip

bp = Blueprint('main', __name__)


@bp.route('/')
@login_required
def index():
    return render_template('index.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            return redirect(url_for('main.index'))
        flash('Invalid credentials')
    return render_template('login.html', form=form)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).first():
            flash('Username already exists')
        else:
            user = User(username=form.username.data, role=form.role.data)
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()
            flash('Registration successful')
            return redirect(url_for('main.login'))
    return render_template('register.html', form=form)


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.login'))


@bp.route('/upload', methods=['GET', 'POST'])
@login_required
def upload_image():
    form = UploadForm()
    if form.validate_on_submit():
        file = form.image.data
        filename = secure_filename(file.filename)
        path = os.path.join('static', filename)
        file.save(path)
        if not detect_helmet(path):
            save_violation(current_user, path)
            flash('Violation detected')
        else:
            flash('Helmet detected')
    return render_template('upload.html', form=form)


@bp.route('/violations')
@login_required
def violations():
    if current_user.role != 'admin':
        user_violations = current_user.violations
    else:
        user_violations = []
        for user in User.query.all():
            user_violations.extend(user.violations)
    return render_template('violations.html', violations=user_violations)


@bp.route('/capture')
@login_required
def capture():
    ip = request.args.get('ip')
    username = request.args.get('username')
    password = request.args.get('password')
    if not ip:
        flash('IP address required')
        return redirect(url_for('main.index'))
    path = capture_image_from_ip(ip, username, password)
    if path and not detect_helmet(path):
        save_violation(current_user, path)
        flash('Violation detected')
    elif path:
        flash('Helmet detected')
    else:
        flash('Failed to capture image')
    return redirect(url_for('main.index'))

ppe_app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PPE Detection</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">PPE Detection</a>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if current_user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{{ url_for('main.violations') }}">Violations</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{{ url_for('main.login') }}">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-4">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="alert alert-info">
            {{ messages[0] }}
          </div>
        {% endif %}
      {% endwith %}
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

ppe_app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h3>Welcome, {{ current_user.username }}!</h3>
<p>Use the options below to upload an image or capture from a camera.</p>
<a class="btn btn-primary" href="{{ url_for('main.upload_image') }}">Upload Image</a>
<form action="{{ url_for('main.capture') }}" method="get" class="mt-3">
  <div class="row g-2 align-items-center">
    <div class="col-auto">
      <input type="text" name="ip" placeholder="Camera IP" class="form-control" required>
    </div>
    <div class="col-auto">
      <input type="text" name="username" placeholder="Username" class="form-control">
    </div>
    <div class="col-auto">
      <input type="password" name="password" placeholder="Password" class="form-control">
    </div>
    <div class="col-auto">
      <button type="submit" class="btn btn-secondary">Capture</button>
    </div>
  </div>
</form>
{% endblock %}

ppe_app/templates/login.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
  {{ form.hidden_tag() }}
  <div class="mb-3">
    {{ form.username.label(class="form-label") }}
    {{ form.username(class="form-control") }}
  </div>
  <div class="mb-3">
    {{ form.password.label(class="form-label") }}
    {{ form.password(class="form-control") }}
  </div>
  {{ form.submit(class="btn btn-primary") }}
  <a href="{{ url_for('main.register') }}">Register</a>
</form>
{% endblock %}

ppe_app/templates/register.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
  {{ form.hidden_tag() }}
  <div class="mb-3">
    {{ form.username.label(class="form-label") }}
    {{ form.username(class="form-control") }}
  </div>
  <div class="mb-3">
    {{ form.password.label(class="form-label") }}
    {{ form.password(class="form-control") }}
  </div>
  <div class="mb-3">
    {{ form.role.label(class="form-label") }}
    {{ form.role(class="form-control") }}
  </div>
  {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock %}

ppe_app/templates/upload.html
{% extends 'base.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
  {{ form.hidden_tag() }}
  <div class="mb-3">
    {{ form.image.label(class="form-label") }}
    {{ form.image(class="form-control") }}
  </div>
  {{ form.submit(class="btn btn-primary") }}
</form>
{% endblock %}

ppe_app/templates/violations.html
{% extends 'base.html' %}
{% block content %}
<h3>Violation Records</h3>
<table class="table">
  <thead>
    <tr>
      <th>Time</th>
      <th>User</th>
      <th>Image</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
  {% for v in violations %}
    <tr>
      <td>{{ v.timestamp }}</td>
      <td>{{ v.user.username }}</td>
      <td><img src="/{{ v.image_path }}" width="100"></td>
      <td>{{ v.description }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}